---
title: "Quant. Mgmt Final"
author: "Mark Christian"
date: "12/16/2020"
output:
  pdf_document: default
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
set.seed(123)  
    

class = c(10,12,11,12,12,12,10,11,11,11,12,12)
class = sample(class, 12, replace = TRUE)
    
taking_pre_college_classes = c(1,2,3,2,1,1,1,2,3,2,1,1)
taking_pre_college_classes = sample(taking_pre_college_classes, 12, replace = TRUE)

gpa = c(3.2,3,4,3.4,3,4,4,3.7,3.4,3.9,4,4)
gpa = sample(gpa, 12, replace = TRUE)
    
data = cbind(  class, taking_pre_college_classes, gpa)
data = as.data.frame(data)
```






```{r}
library(lpSolveAPI)
lprec <- make.lp(0,48)
lp.control(lprec,sense ="max")
set.type(lprec,1:48,"integer")
set.objfn(lprec, rep (c(3.2,3,4,3.4,3,4,4,3.7,3.4,3.9,4,4),4))

```




```{r}
#contrains for the teams 3 because max people in team is 12/4

add.constraint(lprec, c(1, 1, 1, 1, 1 ,1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), "=", 3)
add.constraint(lprec, c( 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1 ,1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), "=", 3)
add.constraint(lprec, c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1 ,1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), "=", 3)
add.constraint(lprec, c( 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1 ,1, 1, 1, 1, 1, 1, 1), "=", 3)

#constrains for students
add.constraint(lprec, c( 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), "=", 1) 
add.constraint(lprec, c( 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), "=", 1)
add.constraint(lprec, c( 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0), "=", 1)
add.constraint(lprec, c( 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0), "=", 1)
add.constraint(lprec, c( 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0), "=", 1)
add.constraint(lprec, c( 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0), "=", 1)
add.constraint(lprec, c( 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0), "=", 1)
add.constraint(lprec, c( 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0), "=", 1)
add.constraint(lprec, c( 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0), "=", 1)
add.constraint(lprec, c( 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0), "=", 1)
add.constraint(lprec, c( 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0), "=", 1)
add.constraint(lprec, c( 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1), "=", 1)



#class level constrain
add.constraint(lprec, c(10,12,11,12,12,12,10,11,11,11,12,12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), ">=", 10)
add.constraint(lprec, c( 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10,12,11,12,12,12,10,11,11,11,12,12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), ">=", 10)
add.constraint(lprec, c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10,12,11,12,12,12,10,11,11,11,12,12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), ">=", 10)
add.constraint(lprec, c( 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10,12,11,12,12,12,10,11,11,11,12,12), ">=", 10)




#taking pre class constrain

add.constraint(lprec, c(1,2,3,2,1,1,1,2,3,2,1,1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), ">=", 0)
add.constraint(lprec, c( 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,2,3,2,1,1,1,2,3,2,1,1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), ">=", 0)
add.constraint(lprec, c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,2,3,2,1,1,1,2,3,2,1,1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), ">=", 0)
add.constraint(lprec, c( 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,2,3,2,1,1,1,2,3,2,1,1), ">=", 0)




#gpa constrain

add.constraint(lprec, c(3.2,3,4,3.4,3,4,4,3.7,3.4,3.9,4,4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), ">=", 10)
add.constraint(lprec, c( 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3.2,3,4,3.4,3,4,4,3.7,3.4,3.9,4,4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), ">=", 10)
add.constraint(lprec, c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3.2,3,4,3.4,3,4,4,3.7,3.4,3.9,4,4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), ">=", 10)
add.constraint(lprec, c( 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3.2,3,4,3.4,3,4,4,3.7,3.4,3.9,4,4), ">=", 10)





```

```{r}
set.bounds(lprec, lower = c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0), columns = c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36))

```

```{r}
lprec

```

```{r}
write.lp(lprec, filename = "finalquanta.lp", type = "lp")

```

```{r}


#decision variable names 

team1 <- as.data.frame(cbind(class, taking_pre_college_classes, gpa))
team2 <- as.data.frame(cbind(class, taking_pre_college_classes, gpa))
team3 <- as.data.frame(cbind(class, taking_pre_college_classes, gpa))
team4 <- as.data.frame(cbind(class, taking_pre_college_classes, gpa))
# Naming the columns and rows.
teams <- as.data.frame(as.matrix(cbind(team1, team2, team3, team4), 12,12))

colnames(teams) <- c("class1", "collclass1", "gpa1", 
                     "class2", "collclass2", "gpa2", 
                     "class3", "collclass3", "gp3a", 
                     "class4", "collclass4", "gpa4")
rownames(teams) <- c("1", "2", "3", 
                     "4", "5", "6", 
                     "7", "8", "9", 
                     "10", "11", "12")
teams

```

teams      student id      gpa avg    coll class    grade
team 1     3,4,9          = 10.5      6             11,12,12
team 2     5, 8, 10       = 12        6             12,12,11
team 3     7, 11, 12      = 9.6       6             12,11,12
team 4     1, 5, 6        = 11.4      5             11,12,12
  


```{r}

library(lpSolveAPI)

finaloutput <- read.lp("finalquanta.lp")
solve(lprec)
get.objective(lprec)
get.variables(lprec)
get.constraints(lprec)

```

team 1 3,4,9
team 2 2, 8, 10
team 3 7, 11, 12
team 4 1, 5, 6


